acme/acme_structure.go, acme/resource_acme_certificate_test.go, acme/test_forwarder_test.go, go.mod, website/docs/r/certificate.html.markdown
This adds the `recursive_nameservers` option to the DNS challenge section
of the acme_certificate resource, allowing for the override of the
system default nameservers used for DNS propagation checks.
This is useful for split-horizon scenarios where Terraform is being run
in a location in the network where a local zone will prevent visibility
into the public TXT records, which will normally cause the provider to
fail, as it will never see the added records.
=> r/certificate: Allow for recursive nameservers to be overridden

acme/acme_structure.go, acme/resource_acme_certificate_test.go, go.mod, go.sum, website/docs/r/certificate.html.markdown
This is to assist with resources/services that take PKCS12 directly, ie:
Azure.
The certificate, intermediate, and private key are all exported into
the PFX archive and the contents are base64 encoded. No password is set.
=> r/certificate: Add PKCS12 export field

acme/acme_migrations.go, acme/acme_migrations_test.go, acme/acme_structure.go, acme/resource_acme_certificate.go
I wrote this provider when my understanding of Terraform was not 100%
complete, this fixes some issues that were the result of that:
* Partial state mode was probably never needed and as such has been
removed. No attributes are set in a way that would produce an
inconsistent state mid-flight.
* Complex structures should be lists, not sets. This prevents odd
hash issues from coming up when changing values in blocks that are
especially restricted to just one element only. dns_challenge is one
of these items and as such has been modified to be a list.
* Not necessarily a mistake in schema design, but `dns_challenge`
configuration items do not need to be ForceNew, as it's perfectly
reasonable that DNS might migrate providers during the lifetime of a
certificate, and since DNS is only used for …
=> r/certificate: No partial, dns_challenge is list, no longer ForceNew

website/docs/r/certificate.html.markdown
The docs for the certificate_p12 still state that the password on the
field is always blank. This changed with #35.
=> docs/r/certificate: certificate_p12 password is configurable

acme/resource_acme_registration_test.go
Let's Encrypt has updated their error message, which caused the
destroy check in TestAccACMERegistration_basic to fail. This update
fixes it so that functions correctly again.
=> r/registration: fix error message pattern in test destroy check

acme/acme_migrations.go, acme/acme_migrations_test.go, acme/acme_structure.go, acme/acme_structure_test.go, acme/resource_acme_certificate.go, acme/resource_acme_certificate_test.go, go.mod, website/docs/dns_providers/index.html.markdown, website/docs/r/certificate.html.markdown
Multiple dns_challenge stanzas can now be specified to present the DNS challenge token. Previously, in situations with multiple primary DNS providers, the challenge may fail if only one provider was presented with the challenge token.
I am open to discussion on how this feature might be implemented. This was just my initial swing at a solution.
=> Add challenge support for multiple DNS providers

logger.go, main.go
The lego library itself logs several useful messages during
operation, namely pertaining to the obtaining of authorizations and
resolution of challenges. However, the lego standard logger conflicts
with Terraform's and these messages do not get displayed.
This adds a lightweight lego StdLogger implementation to pass these
log messages through to the plugin's logging facilities, ensuring
these messages aren't lost.
Log level prefixes are stripped and the messages are ultimately
logged at the DEBUG level.
=> plugin: log lego's log messages in Terraform

acme/resource_acme_certificate.go, go.mod, go.sum, vendor/github.com/go-acme/lego/certificate/certificates.go, vendor/modules.txt
An existing bug with certificate updates means that the
certificate_pem field will be dropped if there are errors renewing.
This does not correct that issue 100% (partial state is needed for
this), but what this *does* do is recover this field by fetching the
certificate data from the CA again if the certificate_pem field is
missing on refresh.
The actual fix to ensure the field is not cleared at all will be
coming in another commit.
=> r/certificate: get certificate from CA if missing in state

acme/resource_acme_certificate.go
This enables partial mode during the update process when the
certificate needs to be renewed.
This to prevent the resource from writing a bad diff if there is an
error during renewal. Specifically, certificate_pem being changed to
an unknown value during diff customization ultimately results in a
blank value being written if a new value is not set during update,
even in the event of an error.
PR #59 corrects existing states that may have been affected by this
issue by pulling the certificate_pem field directly from the CA.
=> r/certificate: use partial mode during certificate renewals

acme/resource_acme_certificate_test.go, acme/resource_acme_registration.go, acme/resource_acme_registration_test.go
This change will remove a deactivated or deleted account from the
state if it's found on refresh. This will allow a destroy plan to
succeed when the account has already been deactivated or is otherwise
missing.
Note that once an account is deactivated, the private key is
unusable, so you cannot use this functionality to delete the resource
and recreate it. You must start a plan with a new private key.
=> r/registration: remove deactivated or deleted accounts on refresh

website/docs/r/certificate.html.markdown
This adds a note that the `certificate_pem` does not include the full certificate chain of the issuer. This was not immediately clear to me, and I came across this by finding this Medium article: https://medium.com/@Temikus/terraform-acme-provider-full-chain-certificates-e25a16d2d036
=> Add note about creating a full certificate chain

website/docs/r/certificate.html.markdown
As per #104 , the documentation is probably wrong as the terraform throws an error when trying to provide the `recursive_nameservers` parameter in the `dns_challenge` block.
=> #104 Misguiding documentation Recursive NS

website/docs/r/certificate.html.markdown
AWS nowadays frequently uses session token - and it took me a considerable time to figure out why I was getting this error:
```
error encountered while presenting token for DNS challenge: route53: InvalidClientTokenId: The security token included in the request is invalid.
```
=> [docs] Route53: use AWS_SESSION_TOKEN (common)

.github/workflows/release.yml, .github/workflows/test.yml, GNUmakefile, acme/certificate_challenges.go, acme/provider_test.go, acme/resource_acme_certificate.go, acme/resource_acme_certificate_test.go, build-support/scripts/memcached-start.sh, build-support/scripts/memcached-stop.sh, docs/resources/certificate.md, go.mod, go.sum
This adds providers for HTTP and TLS challenges, supporting all types currently supported by lego:
* HTTP-01: `http_challenge` represents the in-tool webserver that will answer HTTP challenges. This usually requires escalated privileges to bind the privileged ports, or proxy server access. `http_webroot_challenge` and `http_memcached_challenge` provide alternate challenge types that can potentially work around the networking requirements.
* TLS-ALPN-01: `tls_challenge` represents the in-tool webserver.
We still recommend that you use DNS challenges whenever possible. The addition of the challenges here helps fill a niche that some of our practitioners have where access to DNS is not possible or it is just simpler to use HTTP (possibly single-server deployments, easy access to webroot …
=> r/certificate: HTTP and TLS challenges

acme/resource_acme_certificate.go, acme/resource_acme_certificate_test.go
When creating a CSR also pass the perferred_chain attribute so that you
can control what chain you get. As of writing CSR issuing is broken on
the staging CA because the 'default' chain has expired, and it's not
possible to select an alternate chain.
=> Pass the preferred chain attribute when creating a CSR

docs/index.md, docs/resources/certificate.md, docs/resources/registration.md
In Terraform 0.12 and later, first-class expression can be used to describe variables.
This way seems to be the standard.
https://www.hashicorp.com/blog/terraform-0-12-preview-first-class-expressions
> Terraform uses expressions for dynamic configuration and dependencies. First-class expressions enable variables and operations to be performed outside of strings such as var.foo. In Terraform 0.11 and earlier all expressions were required to be part of interpolations in existing strings, such as "${var.foo}". This simple change has far-ranging benefits, covered in the blog examples.
=> Fix old expression of documents

go.mod, go.sum
To address CVE-2022-41723 dependabot alert.
Note that this is largely superficial. Lots of dependencies seem to require vastly different versions of `x/net`, and to my knowledge there's no HTTP 2 in lego (although go-plugin is a different story). I may revert this if it does not address the alert in our security console.
=> Manually pin golang.org/x/net to v0.7.0

.gitignore, acme/acme_structure.go, acme/acme_structure_test.go, acme/resource_acme_certificate.go, docs/resources/certificate.md
This adds a timeout for the post-certificate request process.
Note that this *only* affects requests after authorization and is the same as setting `--cert.timeout=TIMEOUT` in lego. Timeout for specific DNS providers should still be controlled via their individual provider options.
=> r/certificate: add control for post-auth cert timeout

acme/resource_acme_registration.go
This fixes an issue where, when destroying a registration and re-creating it by doing something like renaming the resources, "inconsistent result after apply" errors may occur.
This was actually a red herring in the fact that it's actually masking other errors that happen during resource creation, such as the fact that a registration with the private key exists, but was deactivated (something that seemingly does not show up during actual creation of an account at Let's Encrypt, I guess).
The fix here should allow these kinds of errors to properly show up.
Fixes #374.
=> r/registration: fix "inconsistent result after apply" errors

acme/data_source_acme_server_url.go, acme/data_source_acme_server_url_test.go, acme/provider.go, docs/data-sources/registration.md, flake.nix
This adds the acme_server_url data source, which gives the current CA server URL that the provider is configured for.
This is a quality-of-life resource designed to make it easier to write modules and configurations that need to depend on the provider's resources downstream.
Fixes #392.
=> d/server_url: new data source

acme/acme_structure.go, acme/acme_structure_test.go, acme/resource_acme_certificate.go, acme/resource_acme_certificate_test.go, docs/resources/certificate.md
This adds the `certificate_serial` computed attribute to the `acme_certificate` resource. This allows you to get the serial number from the certificate, much like the expiry date that is in the `certificate_not_after` field.
=> r/certificate: Add certificate_serial attribute

acme/acme_structure.go, acme/acme_structure_test.go, acme/resource_acme_certificate_test.go, acme/resource_acme_registration.go, acme/resource_acme_registration_test.go, build-support/scripts/pebble-stop.sh, docs/index.md, docs/resources/certificate.md, docs/resources/registration.md
This sets the `private_key_pem` attribute in `acme_registration` to Optional/Computed, allowing the resource to manage the key fully (and hence removing the need to have the key supplied by the likes of `tls_private_key`).
The goal here is to facilitate easier resource management when working with EAB attributes - not needing to supply the private key ensures that you can change the EAB binding, have the old registration deactivated, and the new one activated with a new private key. Without that last
part, registration will fail, as the unchanged private key would still be associated with the deactivated registration. If using the `tls_private_key` resource to supply the key, one would need to taint that
resource, and with other (out-of-band) methods, the private key would need to be …
=> r/registration: Allow private key to be managed by resource

acme/acme_migrations.go, acme/acme_migrations_test.go, acme/resource_acme_registration.go, acme/resource_acme_registration_legacy_schemas.go
The addition of `account_key_algorithm`, `account_key_ecdsa_curve`, and `account_key_rsa_bits` into the configuration with defaults requires a state migration to ensure that the default values are written to state before the first post-upgrade plan happens on existing configurations. This prevents erroneous re-creation of resources that have their keys defined with `tls_private_key` et al.
Fixes #424.
=> r/registration: add state migration

acme/acme_structure.go
This just updates our call for PKCS encoding to use the Modern2023 encryption settings in go-pkcs12; this should ensure secure encryption and compatibility with modern OpenSSL et al.
=> r/cert: use modern PKCS12 encryption

.github/workflows/release.yml
The release process is somewhat disk-heavy. We download a large number of dependencies and also build for a large amount of targets, and for a while now we've seemed to run up on the VM disk space limit on GHA - or so I thought...
Turns out the GHA image is quite bloated and a bit all over the place. The base install has a number of runtimes that we don't need (Dotnet, Android, GHC and CodeQL), Docker images are installed that we don't use, and the disk layout is odd (a 74GB volume in `/mnt` that I don't really understand what it's for, maybe Docker mounts or just arbitrary scratch space). I'm guessing this is for maybe a common build profile, but is totally unnecessary for what we do.
There's https://github.com/easimon/maximize-build-space which was super helpful in figuring this out, …
=> workflows: remove unnecessary stuff from build image for release

acme/resource_acme_certificate.go, acme/resource_acme_certificate_test.go, docs/resources/certificate.md
This is in prep for addressing #485, but it's also been the case for some time that a common name has not only not been required, but not recommended even. This allows you to just skip the common name.
=> r/certificate: Allow no common name to be defined

acme/provider_test.go, acme/resource_acme_certificate.go, acme/resource_acme_certificate_test.go, build-support/pebblecfg/alt-profile.json, build-support/pebblecfg/basic.json, build-support/scripts/pebble-start.sh, build-support/scripts/pebble-stop.sh, docs/resources/certificate.md
This adds the `profile` attribute to `acme_certificate`, allowing you to control the profile used to generate the certificate at the CA.
For example, at Let's Encrypt, this can be used to request a cert without a common name and shorter authorization validity times (`tlsserver`), or one with a shorter lifetime (`shortlived`).
The default is to not request a profile (this is the "classic" profile at Let's Encrypt).
Fixes #485.
=> r/certificate: Add profile support

acme/resource_acme_certificate.go
When the provider renews a certificate, it doesn't mark `certificate_not_after` as newly computed value, so it doesn't show up as a change in the plan. And if this attribute is used as an input to another resource, it will cause the apply to fail as the value changes midway through the apply:
```
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for kubernetes_deployment.service to include
│ new values learned so far during apply, provider
│ "registry.opentofu.org/hashicorp/kubernetes" produced an invalid new
│ value for .spec[0].template[0].spec[0].container[0].env[1].value:
│ was cty.StringVal("2025-07-08T00:56:38Z"), but now
│  cty.StringVal("2025-09-30T04:43:31Z").
│
│ This is a bug in the provider, which should be reported in the
│ provider's own issue …
```
=> r/certificate: Mark certificate_not_after as unknown on renewal

.golangci.yml, acme/acme_migrations.go, acme/acme_migrations_011.go, acme/acme_migrations_test.go, acme/acme_structure.go, acme/acme_structure_test.go, acme/certificate_challenges.go, acme/certificate_challenges_test.go, acme/data_source_acme_server_url.go, acme/dnsplugin/plugin.go, acme/provider.go, acme/resource_acme_certificate.go, acme/resource_acme_registration.go, logger.go
This is just an update to the codebase to clear out a bunch of linter warnings I had:
* Apply all modernize recommendations (mostly `interface{}` -> `any`)
* Add a `.golangci.yml` to the project to exclude errcheck (a notoriously noisy linter that unfortunately does not really conform to common patterns like Terraform's `d.Set()` et al, or `defer something.Close()`)
=> Apply some modernizations and linter stuff
